name: sumanth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25681
title: "Sumanth's Thoughts & Musings"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090504'
    - '#601921'
    - '#676968'
    - '#a9a298'
    - '#9b5a46'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
